name: Build The dist
run-name: ${{ github.actor }} is testing out GitHub Actions MAIN Program
on: 
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run the Server
        run: npm run dev

      - name: build the package
        run: npm run build
        
      - name: Demo it 
        run: echo "🎉 The job was automatically triggered by Mallesh."
