name: Build The dist
run-name: ${{ github.actor }} is testing out GitHub Actions MAIN Program
on: 
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Demo it 
        run: echo "🎉 The job was automatically triggered by Mallesh."
