name: Build The dist
run-name: ${{ github.actor }} is testing out GitHub Actions MAIN Program
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎉 The job was automatically triggered by Mallesh."
